steps:
  # Build the frontend image
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - --destination=us-docker.pkg.dev/$PROJECT_ID/gcr.io/frontend
      - --cache=true
      - --dockerfile=./client/Dockerfile
      - --context=dir://client
      - --build-arg=DEPLOY_TARGET=production
  # Build the LSP image
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - --destination=us-docker.pkg.dev/$PROJECT_ID/gcr.io/lsp
      - --cache=true
      - --dockerfile=./lsp/Dockerfile
      - --context=dir://lsp
  # Build the sandbox image
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - --destination=us-docker.pkg.dev/$PROJECT_ID/gcr.io/sandbox
      - --cache=true
      - --dockerfile=./server/Dockerfile
      - --context=dir://server
