steps:
  # Build the frontend image
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - --destination=gcr.io/$PROJECT_ID/frontend
      - --cache=true
      - --dockerfile=./client/Dockerfile
      - --context=dir://client
  # Build the LSP image
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - --destination=gcr.io/$PROJECT_ID/lsp
      - --cache=true
      - --dockerfile=./lsp/Dockerfile
      - --context=dir://lsp
  # Build the sandbox image
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - --destination=gcr.io/$PROJECT_ID/sandbox
      - --cache=true
      - --dockerfile=./server/Dockerfile
      - --context=dir://server
