version: "3.8"
services:
  caddy:
    build: .
    container_name: caddy
    ports:
      - "8080:8080"
  client:
    build:
      context: client
    container_name: client
    stdin_open: true
    tty: true
    ports:
      - "8082:8080"
    volumes:
      - /app/node_modules
      - /Users/yogesh/projects/bokeh-play/client:/app
    environment:
      - NUXT_APP_BACKEND_URL=http://localhost:8080/sandbox
      - NUXT_APP_LSP_URL=ws://localhost:8080/sandbox/lsp/
  sandbox:
    build: server
    container_name: sandbox
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "8000:8000"
      - "8081:8081"
      - "5000:8080"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
      - "5004:5004"
      - "5005:5005"
      - "5006:5006"
      - "5007:5007"
      - "5008:5008"
      - "5009:5009"
      - "5010:5010"
    volumes:
      - /Users/yogesh/projects/bokeh-play/server:/app
      - /app/sandbox/static/envs
      - /app/lsp/node_modules
    environment:
      LSP_PORT: 8081
      PROJECTS_DIR: /projects
  # emulators:
  #   build:
  #     context: client
  #     dockerfile: Dockerfile-emulators
  #   ports:
  #     - "10000-10004"
  #   volumes:
  #     - /app/node_modules
  #     - /Users/yogesh/projects/bokeh-play/client:/app
