version: "3.8"
services:
  caddy:
    build: .
    container_name: caddy
    ports:
      - "8080:8080"
  client:
    build:
      context: client
    container_name: client
    stdin_open: true
    tty: true
    volumes:
      - /app/node_modules
      - /Users/yogesh/projects/bokeh-play/client:/app
    env_file:
      - client/envs/.env.development.local
  sandbox:
    build: server
    container_name: sandbox
    ports:
      - "5000:8080"
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - /Users/yogesh/projects/bokeh-play/server:/app
      - /app/sandbox/static/envs
      - /app/lsp/node_modules
    environment:
      - LSP_PORT=8081
      - ORIGIN_DOMAIN=localhost:8080
      - PROJECTS_DIR=/projects
      - DEPLOY_TARGET=staging
  # emulators:
  #   build:
  #     context: client
  #     dockerfile: Dockerfile-emulators
  #   ports:
  #     - "10000-10004"
  #   volumes:
  #     - /app/node_modules
  #     - /Users/yogesh/projects/bokeh-play/client:/app
