version: "3.8"
services:
  caddy:
    build: .
    container_name: caddy
    ports:
      - "8080:8080"
  lsp:
    build: lsp
    container_name: lsp
    stdin_open: true
    tty: true
  sandbox1:
    build: server
    container_name: sandbox1
    stdin_open: true
    tty: true
    restart: always
    env_file:
      - server/envs/.env.staging.local
    environment:
      - SERVICE_NAME=sandbox1
  sandbox2:
    image: bokeh-play_sandbox1
    container_name: sandbox2
    stdin_open: true
    tty: true
    restart: always
    env_file:
      - server/envs/.env.staging.local
    environment:
      - SERVICE_NAME=sandbox2
