version: "3.8"
services:
  caddy:
    build:
      context: client
      args: DEPLOY_TARGET=${DEPLOY_TARGET}
    container_name: caddy
    ports:
      - "8080:8080"
  lsp:
    build: lsp
    container_name: lsp
  sandbox1:
    build: server
    container_name: sandbox1
    restart: always
    env_file:
      - server/envs/.env.${DEPLOY_TARGET}.local
    environment:
      - SERVICE_NAME=sandbox1
  sandbox2:
    image: bokeh-play_sandbox1
    container_name: sandbox2
    restart: always
    env_file:
      - server/envs/.env.${DEPLOY_TARGET}.local
    environment:
      - SERVICE_NAME=sandbox2
