version: "3.8"
services:
  caddy:
    build: .
    container_name: caddy
    ports:
      - "8080:8080"
  client:
    build:
      context: client
    container_name: client
    stdin_open: true
    tty: true
    volumes:
      - /app/node_modules
      - /Users/yogesh/projects/bokeh-play/client:/app
    env_file:
      - client/envs/.env.development.local
  sandbox1:
    build: server
    container_name: sandbox1
    ports:
      - "5000:8080"
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - /Users/yogesh/projects/bokeh-play/server:/app
      - /app/sandbox/static/envs
      - /app/lsp/node_modules
    env_file:
      - server/envs/.env.development.local
    environment:
      - SERVICE_NAME=sandbox1
  sandbox2:
    build: server
    container_name: sandbox2
    ports:
      - "5001:8080"
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - /Users/yogesh/projects/bokeh-play/server:/app
      - /app/sandbox/static/envs
      - /app/lsp/node_modules
    env_file:
      - server/envs/.env.development.local
    environment:
      - SERVICE_NAME=sandbox2
  # emulators:
  #   build:
  #     context: client
  #     dockerfile: Dockerfile-emulators
  #   ports:
  #     - "10000-10004"
  #   volumes:
  #     - /app/node_modules
  #     - /Users/yogesh/projects/bokeh-play/client:/app
