version: "3.8"
services:
  lsp:
    build: lsp
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - /app/node_modules
      - /Users/yogesh/projects/bokeh-play/lsp:/app
  # emulators:
  #   build:
  #     context: client
  #     dockerfile: Dockerfile-emulators
  #   ports:
  #     - "10000-10004"
  #   volumes:
  #     - /app/node_modules
  #     - /Users/yogesh/projects/bokeh-play/client:/app
  client:
    build: client
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - /Users/yogesh/projects/bokeh-play/client:/app
    environment:
      - VUE_APP_BACKEND_URL=http://localhost:5000
  server:
    build: server
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
      - "5004:5004"
      - "5005:5005"
      - "5006:5006"
      - "5007:5007"
      - "5008:5008"
      - "5009:5009"
      - "5010:5010"
    volumes:
      - /Users/yogesh/projects/bokeh-play/server:/app
    environment:
      PROJECTS_DIR: /projects
