apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccount: sandbox-service-account
      containers:
        - name: server
          image: server:latest
          resources:
            limits:
              cpu: "400m"
              memory: "400Mi"
            requests:
              cpu: "200m"
              memory: "200Mi"
          env:
            - name: ORIGIN_DOMAIN
              value: "127.0.0.1:4503"
            - name: ORIGIN_PROTOCOL
              value: http
