steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/sandbox", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/sandbox"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "sandbox1", # change to your service name
        "--image",
        "gcr.io/$PROJECT_ID/sandbox",
        "--max-instances",
        "1",
        "--memory",
        "1024M",
        "--concurrency",
        "10",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
      # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
        "run",
        "deploy",
        "sandbox2", # change to your service name
        "--image",
        "gcr.io/$PROJECT_ID/sandbox",
        "--max-instances",
        "1",
        "--memory",
        "1024M",
        "--concurrency",
        "10",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
images:
  - gcr.io/$PROJECT_ID/sandbox
