apiVersion: v1
kind: Service
metadata:
  name: lsp
  labels:
    app: lsp
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: lsp
