apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox
  labels:
    app: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      containers:
        - name: sandbox
          image: sandbox:latest
          resources:
            limits:
              cpu: "250m"
              memory: "250Mi"
            requests:
              cpu: "100m"
              memory: "250Mi"
          env:
            - name: ORIGIN_DOMAIN
              value: "127.0.0.1:4503"
            - name: ORIGIN_PROTOCOL
              value: http
